apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
helmCharts:
  - name: victoria-metrics-k8s-stack
    repo: https://victoriametrics.github.io/helm-charts/
    version: 0.21.0
    releaseName: victoriametrics
    namespace: monitoring
    valuesFile: values.yaml
    includeCRDs: true
