apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alloy
helmCharts:
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    version: 1.10.0
    releaseName: alloy
    namespace: alloy
    valuesFile: values.yaml
